### PR TITLE
Adding nwb tutorial

### PR DESCRIPTION
**Pull request by h-mayorquin**
As in the title.

### CODE REVIEW

**Comment by alejoe91** [comment]
@h-mayorquin I know this is still a draft, but a few comments:

- I would just show the `add_recording` / `write_recording` and `add_sorting` / `write_sorting` and explain how internally other NWB metadata are compiled
- I think we can make the `SortingAnalyzer` work. This [PR](https://github.com/catalystneuro/neuroconv/pull/821) is working on my side, if we have time we can try it out!

**Comment by h-mayorquin** [comment]
No, thanks for the advice.
* I will add the writers.
* What do you mean about the metadata? Can you providen an example, as in, do you mean the metadata that is passed or the metadata that ends in the file? For the later I have properties but I don't know.
* For the sorter analyzer I am skeptical, I don't want to have things that are not finished. What aspect are you more interested in illustrate? The waveforms meand and stds? The electrode mapping?

**Comment by samuelgarcia** [comment]
Honestly sorting/recording is enough  ? no I woule also skip the analyzer
the streaming demo is cool.

It would be cool to show this on dandi hub platform no ?

And why are mocking a nwb file, why not creating a real and new file ?

**Comment by h-mayorquin** [comment]
@samuelgarcia you are right about creating an nwbfile. Mocks should be used for testing. I will change this.

@alejoe91 let me know what you mean with your comment about metadata (I honestly did not get it) to improve this. I will try to make the sorting analyzer thing before the event.

**Comment by samuelgarcia** [comment]
I merge this now.
Feel free to push more update and open new PR

**Pull request merged**
